api/urls.py
from django.urls import path

from . import views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
    openapi.Info(
        title="Allotr API",
        default_version="v1",
        description="A REST API for the Allotr Course Allocation system",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="ssali.jkigundu@student.utamu.ac.ug"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("allocations", views.AllocationListView.as_view(), name="allocation-list"),
    path("courses/", views.CourseListView.as_view(), name="course_api_list"),
    path("intakes/", views.IntakeListView.as_view(), name="intake_api_list"),
    path(
        "enrollments/", views.EnrollmentListView.as_view(), name="enrollment_api_list"
    ),
    path("programs/", views.ProgramListView.as_view(), name="program_api_list"),
    path(
        "program/<int:program_id>/",
        views.ProgramDetailView.as_view(),
        name="program_detail",
    ),
    path(
        "programs-in-department/department/<int:department_id>/",
        views.ProgramsInDepartmentView.as_view(),
        name="programs_in_department_api_list",
    ),
    path(
        "enrollment/<int:pk>/",
        views.EnrollmentDetailUpdateView.as_view(),
        name="enrollment_api_list",
    ),
    path(
        "programcourses/",
        views.ProgramCourseListView.as_view(),
        name="program_course_api_list",
    ),
    path(
        "courses-in-program/<int:program_id>/",
        views.CoursesInProgramListView.as_view(),
        name="courses_in_program",
    ),
    path(
        "list_allocations/",
        views.ListAllocationView.as_view(),
        name="list_allocations_matching",
    ),
    path("lecturers/", views.LecturerList.as_view(), name="lecturer_api_list"),
    path(
        "lecturers/<int:lecturer_id>/",
        views.LecturerDetailView.as_view(),
        name="lecturer_api_detail",
    ),
    path(
        "structures/<int:program_id>/",
        views.StructureView.as_view(),
        name="structure_view",
    ),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path("auth/", include("users.urls"), name="auth"),
    path("", include("home.urls"), name="home"),
    path("i18n/", include("django.conf.urls.i18n")),
    path("courses/", include("courses.urls")),
    path("programs/", include("programs.urls")),
    path("departments/", include("departments.urls")),
    path("schools/", include("schools.urls")),
    path("intakes/", include("intakes.urls")),
    path("enrollments/", include("enrollments.urls")),
    path("allocations/", include("allocations.urls")),
    path("lecturers/", include("lecturers.urls")),
    path("api/", include("api.urls")),
]

departments/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.DepartmentListView.as_view(), name="department_list"),
    path("create/", views.create_department, name="create_department"),
    path("<int:pk>/", views.DepartmentDetailView.as_view(), name="department_detail"),
    path(
        "update/<int:department_id>/", views.update_department, name="department_update"
    ),
    path("delete/<int:pk>/", views.delete_department, name="delete_department"),
]

departments/models.py
from django.db import models
from schools.models import School

# Create your models here.


class Department(models.Model):
    name = models.CharField(max_length=500)
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    code = models.CharField(max_length=6)
    department_head = models.CharField(max_length=255)
    contact_email = models.EmailField(max_length=80)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name

departments/forms.py
from django import forms

from .models import Department


class DepartmentUpdateForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={"rows": 5}))

    class Meta:
        model = Department
        fields = ["name", "department_head", "contact_email", "description"]


class DepartmentCreateForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={"rows": 5}))

    class Meta:
        model = Department
        fields = ["name", "department_head", "school", "contact_email", "description"]

departments/views.py
import json
from typing import Any

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from programs.models import Program

from .forms import DepartmentCreateForm
from .models import Department

# Create your views here.


class DepartmentListView(LoginRequiredMixin, ListView):
    template_name = "departments/index.html"
    queryset = Department.objects.all()
    context_object_name = "departments"

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)

        context["form"] = DepartmentCreateForm()

        return context


class DepartmentDetailView(LoginRequiredMixin, DetailView):
    template_name = "departments/detail.html"
    queryset = Department.objects.all()
    context_object_name = "department"

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)

        context["departments"] = Department.objects.all()
        context["programs"] = Program.objects.all().filter(department=self.get_object())
        return context


@login_required
def create_department(request):
    if request.method == "POST":
        data = request.POST
        form = DepartmentCreateForm(data=data)

        if form.is_valid():
            form.save()

            messages.success(request, "Department created successfully")

            return redirect(reverse("department_list"))

    return redirect(reverse("department_list"))


@login_required
def update_department(request: HttpRequest, department_id):
    department_to_update = Department.objects.filter(pk=department_id)

    print(request.is_ajax())

    if request.method == "POST" and request.is_ajax():
        data = json.loads(request.body)

        print(data)

        department_to_update.update(
            name=data.get("name"),
            description=data.get("description"),
            department_head=data.get("department_head"),
            contact_email=data.get("contact_email"),
        )

        messages.success(
            request,
            f"Department '{department_to_update.first().name}' has been updated successfully",
        )

        return JsonResponse(data={"message": "Updated Successfully"})

    return JsonResponse(data={"message": "Hello from server"})


@login_required
def delete_department(request, pk):
    department = get_object_or_404(Department, id=pk)

    department.delete()

    messages.success(request, f"Department {department.name} deleted successfully")

    return redirect(reverse("department_list"))

templates/departments/detail.html
{% extends 'layouts/base.html' %} {% load static %} {% load crispy_forms_tags %}
{% block title %} Tables {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
{{ form.media.css }}
<style></style>
{% endblock stylesheets %} {% block content %}

<div class="container-fluid py-4" id="app">
  <div class="row">
    <div class="col-12">
      <div class=" mb-4">
        <div class="card-header pb-0">
          <h3>{{department.name}}</h3>
        </div>
        <div class="card-body px-0 pt-0 pb-2">
          <div class="container container-fluid">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item" role="presentation">
                <button
                  class="nav-link active"
                  id="home-tab"
                  data-bs-toggle="tab"
                  data-bs-target="#home"
                  type="button"
                  role="tab"
                  aria-controls="home"
                  aria-selected="true"
                >
                  Details
                </button>
              </li>
              <li class="nav-item" role="presentation">
                <button
                  class="nav-link"
                  id="profile-tab"
                  data-bs-toggle="tab"
                  data-bs-target="#profile"
                  type="button"
                  role="tab"
                  aria-controls="profile"
                  aria-selected="false"
                >
                  Programs
                </button>
              </li>
            </ul>
            <div class="tab-content mt-4" id="myTabContent">
              <div
                class="tab-pane fade show active"
                id="home"
                role="tabpanel"
                aria-labelledby="home-tab"
              >
                <h5 class="mb-3">Department Details</h5>
                <div class="row">
                  <div class="col-md-6">
                    <h6>Department Head</h6>
                    <p>{{department.department_head}}</p>
                    <h6>Department Details</h6>
                    <p>{{ department.description }}</p>
                  </div>
                  <div class="col-md-6">
                    <h6>School</h6>
                    <p>{{department.school}}</p>
                    <h6>Contact Email</h6>
                    <p>{{department.contact_email}}</p>
                   
                  </div>
                </div>
              </div>
              <div
                class="tab-pane fade"
                id="profile"
                role="tabpanel"
                aria-labelledby="profile-tab"
              >
                <h6>Programs Offered under this program</h6>
                <div class="card-body px-0 pt-0 pb-2">
                  <div id="programTable" class="table-responsive p-0">
                  
                  </div>

                    <div class="modal modal-lg fade " id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
                        <div class="modal-dialog modal-dialog-centered" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">Update Program Programs</h5>
                              <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                          <form action="" method="post">
                            <div class="modal-body" style="overflow-y: scroll; height:400px;">
                              {% csrf_token %}
                              {{ form|crispy }}
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-sm bg-gradient-secondary" data-bs-dismiss="modal">Close</button>
                              <button type="submit" class="btn btn-sm bg-gradient-dark">Save changes</button>
                            </div>
                          </form>
                          </div>
                        </div>
                      </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% include "includes/footer.html" %}
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
{{ form.media.js }}

<script>
  const degreeLevelFormatter =(cell, formatterParams, onRendered)=>{
    let value = cell.getValue();
    if (value == 'D'){return "Diploma";}
    else if (value == "B") return "Bachelor's";
    else if (value == "PGd") return "Post Graduate Diploma";
    else if (value == "M") return "Master's"
  }
  let id = 1;
  let table = new Tabulator("#programTable",{
    ajaxURL: `${window.location.origin}/api/programs-in-department/department/${id}/`,
    layout:'fitColumns',
    columns:[                 //define the table columns
        {title:"id", field:"id",width:100},
        {title:"Code", field:"code"},
        {title:"Name", field:"name", width:95},
        {title:"Degree Level", field:"degree_level",formatter:degreeLevelFormatter},
    ],
  })



</script>
{% endblock javascripts %}

templates/departments/index.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Tables {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="container-fluid py-4" id="app">

  <div class="row">
    <div class="col-12">
      <div class="card mb-4">
        <div class="card-header pb-0">
          <h6>Departments</h6>
        </div>
        <div class="card-header pb-0">
          <button type="button" class="btn btn-sm bg-gradient-dark" data-bs-toggle="modal"
            data-bs-target="#departmentCreateModal">
            Add Department
          </button>
        </div>

        <div class="card-body px-0 pt-0 pb-2">
          <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
              <thead>
                <tr>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Department Name</th>
                </tr>
              </thead>
              <tbody>

                {% for department in departments %}
                <tr>
                  <td>
                    <div class="d-flex px-2 py-1">
                      <div>
                        <img src="{% static 'assets/img/grad.png' %}" class="avatar avatar-sm me-3" alt="user1">
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="mb-0 text-sm">{{department.name}}</h6>
                        <p class="text-xs text-secondary mb-0">{{ department.contact_email }}</p>
                      </div>
                    </div>
                  </td>
                  <td>
                    <p class="text-xs font-weight-bold mb-0">School</p>
                    <p class="text-xs text-secondary mb-0">{{department.school}}</p>
                  </td>
                  <td class="align-middle">
                    <button type="button"
                      @click="setCourseUpdate(`{{department.id}}`,`{{department.name}}`,`{{department.department_head}}`,`{{department.contact_email}}`,`{{department.description}}`)"
                      class="btn btn-sm bg-gradient-dark" data-bs-toggle="modal" data-bs-target="#exampleModal">
                      Details
                    </button>
                  </td>
                </tr>
                {% endfor %}

              </tbody>
            </table>


            {% comment %}
            A department update and detail form
            {% endcomment %}

            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
              aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Department Info</h5>
                    <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <form>
                      {% csrf_token %}


                      <div id="div_id_name" class="form-group"> <label for="id_name" class=" requiredField">
                          Name<span class="asteriskField">*</span> </label>
                        <div>
                          <input required type="text" name="name" maxlength="500" class="textinput form-control"
                            required id="id_name" :value=[[name]]>
                        </div>
                      </div>
                      <div id="div_id_department_head" class="form-group"> <label for="id_department_head"
                          class=" requiredField">
                          Department head<span class="asteriskField">*</span> </label>
                        <div>
                          <input required type="text" name="department_head" maxlength="255"
                            class="textinput form-control" required id="id_department_head" :value=[[department_head]]
                            @input="event => department_head = event.target.value">
                        </div>
                      </div>
                      <div id="div_id_contact_email" class="form-group"> <label for="id_contact_email"
                          class=" requiredField">
                          Contact email<span class="asteriskField">*</span> </label>
                        <div>
                          <input required type="email" name="contact_email" maxlength="80"
                            class="emailinput form-control" required id="id_contact_email" :value=[[contact_email]]>
                        </div>
                      </div>
                      <div id="div_id_description" class="form-group"> <label for="id_description"
                          class=" requiredField">
                          Description<span class="asteriskField">*</span> </label>
                        <div>
                          <textarea name="description" cols="40" rows="5" class="textarea form-control" required
                            id="id_description">[[description]]</textarea>
                        </div>
                      </div>

                    </form>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn bg-gradient-secondary" data-bs-dismiss="modal"
                      @click="resetState">Close</button>
                    <button type="button" @click="updateCourse()" class="btn bg-gradient-primary">Update
                      Department</button>
                    <a href="#" class="btn bg-gradient-danger" data-bs-toggle="modal"
                      data-bs-target="#deleteModal">Delete Department</a>
                  </div>
                </div>
              </div>
            </div>

            {% comment %}
            department Create form
            {% endcomment %}
            <div class="modal fade" id="departmentCreateModal" tabindex="-1" role="dialog"
              aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Create Department</h5>
                    <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close" @click="resetState()">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <form method="post" action="{% url 'create_department' %}">
                      {% csrf_token %}
                      {{form|crispy}}
                      <div class="modal-footer">
                        <button type="button" @click="resetState()" class="btn bg-gradient-dark"
                          data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn bg-gradient-primary">Save</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>

            {% comment %}
            Modal for deleting department
            {% endcomment %}
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="modal-notification"
              aria-hidden="true">
              <div class="modal-dialog modal-danger modal-dialog-centered modal-" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h6 class="modal-title" id="modal-title-notification">Delete Department</h6>
                    <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close" @click="resetState()">
                      <span aria-hidden="true">×</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <div class="py-3 text-center">
                      <i class="ni ni-bell-55 ni-3x"></i>
                      <h4 class="text-gradient text-danger mt-4">Are you sure you want to delete this department?</h4>
                      <p>[[name]]</p>
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn bg-gradient-danger" @click="deleteDepartment()">Ok, Delete</button>
                    <button type="button" class="btn bg-gradient-dark text-white ml-auto"
                      data-bs-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script>

  const app = Vue.createApp({
    mounted() {

    },
    data() {
      return {
        count: 0,
        id: '',
        name: '',
        department_head: '',
        contact_email: '',
        description: ''
      }
    },
    delimiters: ['[[', ']]'],
    methods: {
      setCourseUpdate(id, name, department_head, email, description) {
        this.name = name
        this.department_head = department_head
        this.contact_email = email
        this.description = description
        this.id = id
      },
      resetState() {
        this.name = ''
        this.department_head = ''
        this.contact_email = ''
        this.description = ''
      },
      async updateCourse() {
        const tokenField = document.querySelector('input[name="csrfmiddlewaretoken"]');


        let csrfToken = tokenField.value;

        const body = {
          id: this.id,
          name: document.querySelector('#id_name').value,
          department_head: document.querySelector('#id_department_head').value,
          contact_email: document.querySelector('#id_contact_email').value,
          description: document.querySelector('#id_description').value
        }

        console.log(body)


        const response = await fetch(`/departments/update/${this.id}/`, {
          method: 'POST',
          body: JSON.stringify(body),
          headers: {
            'Content-Type': 'Application/Json',
            'X-CSRFToken': csrfToken,
            'X-Requested-With': 'XMLHttpRequest'
          }
        });



        const data = await response.json()


        this.name = ''
        this.department_head = ''
        this.contact_email = ''
        this.description = ''

        window.location.reload()
      },
      async deleteDepartment() {
        const response = await fetch(`/departments/delete/${this.id}/`);


        const data = response.json();

        console.log(data)

        window.location.reload()
      }
    }


  }).mount('#app')

</script>
{% endblock javascripts %}