api/urls.py
from django.urls import path

from . import views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
    openapi.Info(
        title="Allotr API",
        default_version="v1",
        description="A REST API for the Allotr Course Allocation system",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="ssali.jkigundu@student.utamu.ac.ug"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("allocations", views.AllocationListView.as_view(), name="allocation-list"),
    path("courses/", views.CourseListView.as_view(), name="course_api_list"),
    path("intakes/", views.IntakeListView.as_view(), name="intake_api_list"),
    path(
        "enrollments/", views.EnrollmentListView.as_view(), name="enrollment_api_list"
    ),
    path("programs/", views.ProgramListView.as_view(), name="program_api_list"),
    path(
        "program/<int:program_id>/",
        views.ProgramDetailView.as_view(),
        name="program_detail",
    ),
    path(
        "programs-in-department/department/<int:department_id>/",
        views.ProgramsInDepartmentView.as_view(),
        name="programs_in_department_api_list",
    ),
    path(
        "enrollment/<int:pk>/",
        views.EnrollmentDetailUpdateView.as_view(),
        name="enrollment_api_list",
    ),
    path(
        "programcourses/",
        views.ProgramCourseListView.as_view(),
        name="program_course_api_list",
    ),
    path(
        "courses-in-program/<int:program_id>/",
        views.CoursesInProgramListView.as_view(),
        name="courses_in_program",
    ),
    path(
        "list_allocations/",
        views.ListAllocationView.as_view(),
        name="list_allocations_matching",
    ),
    path("lecturers/", views.LecturerList.as_view(), name="lecturer_api_list"),
    path(
        "lecturers/<int:lecturer_id>/",
        views.LecturerDetailView.as_view(),
        name="lecturer_api_detail",
    ),
    path(
        "structures/<int:program_id>/",
        views.StructureView.as_view(),
        name="structure_view",
    ),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path("auth/", include("users.urls"), name="auth"),
    path("", include("home.urls"), name="home"),
    path("i18n/", include("django.conf.urls.i18n")),
    path("courses/", include("courses.urls")),
    path("programs/", include("programs.urls")),
    path("departments/", include("departments.urls")),
    path("schools/", include("schools.urls")),
    path("intakes/", include("intakes.urls")),
    path("enrollments/", include("enrollments.urls")),
    path("allocations/", include("allocations.urls")),
    path("lecturers/", include("lecturers.urls")),
    path("api/", include("api.urls")),
]

courses/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.CourseListView.as_view(), name="course_list"),
    path("update/<int:course_id>", views.update_course, name="update_course"),
]

courses/models.py
from django.db import models

# Create your models here.


class Course(models.Model):
    code = models.CharField(max_length=10, unique=True)
    title = models.CharField(max_length=225)
    course_description = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.code} {self.title}"

courses/forms.py
from django import forms

from .models import Course


class CourseUpdateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ["code", "title", "course_description"]


class CourseCreateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ["code", "title", "course_description"]

        widgets = {"course_description": forms.Textarea(attrs={"rows": 5})}

courses/views.py
import json
from typing import Any

from courses.models import Course
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView

from .forms import CourseCreateForm, CourseUpdateForm

# Create your views here.


# @login_required(login_url='/auth/login/')
class CourseListView(LoginRequiredMixin, ListView):
    template_name = "courses/index.html"
    queryset = Course.objects.all()
    context_object_name = "courses"

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)

        context["update_form"] = CourseUpdateForm()
        context["form"] = CourseCreateForm()

        return context

    def post(self, request, *args, **kwargs):
        form = CourseCreateForm(self.request.POST)

        if form.is_valid():
            form.save()
            messages.success(self.request, "Course created successfully")
            return redirect(reverse("course_list"))


@login_required
def update_course(request: HttpRequest, course_id):
    course_to_update = Course.objects.filter(id=course_id)
    if request.method == "POST" and request.is_ajax():
        data = json.loads(request.body)

        course_to_update.update(
            code=data.get("code"),
            title=data.get("title"),
            course_description=data.get("course_description"),
        )

        messages.success(
            request,
            f"Course '{course_to_update.first().title}' has been updated successfully!",
        )

        return JsonResponse(data={"message": "Course Updated successfully"})

    return JsonResponse(data={"message": "Hello from server"})

templates/courses/index.html
{% extends 'layouts/base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block title %} Courses {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<style>
  .jexcel {
    /* Set a border for the entire jExcel table */
    color: black;
  }

  .jexcel thead th {
    color: white;
    background-color: #31385F;
  }
</style>
{% endblock stylesheets %}

{% block content %}

<div class="container card mb-4  py-4" id="app">
  <div class="row">
    <div class="col-12">
      <div class="card-header pb-0">
        <h3>Courses</h3>
        <button type="button" class="btn btn-sm bg-gradient-dark" data-bs-toggle="modal"
          data-bs-target="#ProgramCreateModal">
          Add Course
        </button>
      </div>
      <div class="">
        <div class="card-body px-0 pt-0 pb-2 ">
          {% comment %}
          course table
          {% endcomment %}
          <p class="loading text-center" style="display: none;"><img src="{% static 'assets/img/loading.gif' %}" width="50"></p>
          <div class="row">
            <div class="col-md-3">
              <select id="filter-field" class="form-select">
                <option></option>
                <option value="code">Code</option>
                <option value="title">Title</option>
              </select>
            </div>
            <div class="col-md-4">
              <input id="filter-value" class="form-control" type="text" placeholder="Value to filter">
            </div>
            <div class="col-md-3">
              <button id="filter-clear" class="btn btn-sm btn-dark"><i class="fa fa-filter" aria-hidden="true"></i>
              </button>
            </div>
          </div>
          <div id="spreadsheet"></div>
          {% comment %}
          modal for creating a course
          {% endcomment %}

          <div class="modal modal-lg fade" id="ProgramCreateModal" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalLabel" aria-hidden="true">

            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">
                    Create Course
                  </h5>
                  <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close"
                    @click="resetState()">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <form method="post" action="" id="create-form">
                    {% csrf_token %}
                    <div class="row">
                      <div class="col">
                        {{form.title|as_crispy_field}}
                      </div>
                      <div class="col">
                        {{ form.code|as_crispy_field }}
                      </div>
                    </div>
                    <div class="form-group">
                      {{ form.course_description|as_crispy_field }}
                    </div>
                    <div class="modal-footer">
                      <button type="submit" class="btn btn-sm btn-dark">
                        Save
                      </button>
                      <button type="button" @click="resetState()" class="btn btn-sm btn-link" data-bs-dismiss="modal">
                        Close
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
          {% comment %}
          form for updating a course
          {% endcomment %}

          <div class="modal fade" id="modal-default" tabindex="-1" role="dialog" aria-labelledby="modal-default"
            aria-hidden="true">
            <div class="modal-dialog modal- modal-dialog-centered modal-" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h6 class="modal-title" id="modal-title-default">[[code]] [[title]]</h6>
                  <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close"
                    @click="resetState()">
                    <span aria-hidden="true">×</span>
                  </button>
                </div>
                <div class="modal-body">
                  <form action="">
                    {% csrf_token %}
                    <div id="div_id_code" class="form-group"> <label for="id_code" class=" requiredField">
                        Code<span class="asteriskField">*</span> </label>
                      <div>
                        <input type="text" name="code" maxlength="10" class="textinput form-control" required
                          id="id_code" v-model="code">
                      </div>
                    </div>
                    <div id="div_id_title" class="form-group"> <label for="id_title" class=" requiredField">
                        Title<span class="asteriskField">*</span> </label>
                      <div>
                        <input type="text" name="title" maxlength="225" class="textinput form-control" required
                          id="id_title" v-model="title">
                      </div>
                    </div>
                    <div id="div_id_course_description" class="form-group"> <label for="id_course_description"
                        class=" requiredField">
                        Course description<span class="asteriskField">*</span> </label>
                      <div>
                        <textarea name="course_description" v-model="course_description" cols="40" rows="5"
                          class="textarea form-control" required id="id_course_description"></textarea>
                      </div>
                    </div>
                  </form>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-sm bg-gradient-dark" @click="updateCourse()">Update
                    Course</button>
                  <button type="button" class="btn btn-link  ml-auto" data-bs-dismiss="modal"
                    @click="resetState()">Close</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script>
  // create a vue app inside this template
  const app = Vue.createApp({
    data() {
      return {
        title: '',
        code: '',
        course_description: '',
        url:window.location.origin
      };
    },
    delimiters: ['[[', ']]'],
    mounted() {
      const loading = document.querySelector('.loading');

      //Define variables for input elements
      var fieldEl = document.getElementById("filter-field");
      var typeEl = document.getElementById("filter-type");
      var valueEl = document.getElementById("filter-value");



      loading.style.display = "block";

      fetch(`${this.url}/api/courses`)
        .then(response => {
          if (!response.ok) {
            throw new Error('Network response was not ok');
          }
          return response.json();
        })
        .then(data => {
          setTimeout(() => {
            loading.style.display = 'none';


            const rows = data.map(item => ({
              id: item.id,
              code: item.code,
              title: item.title,
              course_description: item.course_description,
              created_at: this.formatReadableDate(item.created_at)
            }));

            var openIcon = function (value, data, cell, row, options) { //plain text value
              return "<i class='fa fa-search'></i>"
            };

            var table = new Tabulator("#spreadsheet", {
              data: rows, //assign data to table
              autoColumns: true, //create columns from data field names
              layout: "fitColumns",      //fit columns to width of table
              responsiveLayout: "hide",  //hide columns that don't fit on the table
              addRowPos: "top",          //when adding a new row, add it to the top of the table
              history: true,             //allow undo and redo actions on the table
              pagination: "local",       //paginate the data
              paginationSize: 10,         //allow 7 rows per page of data
              paginationCounter: "rows", //display count of paginated rows in footer
              movableColumns: true,
              columns: [                 //define the table columns
                { title: "code", field: "code", editor: "input" },
                { title: "Title", field: "title" },
                { title: "created_at", field: "created_at" },
                { title: "action", sortable: false, formatter: openIcon },
              ],
            });


            //Update filters on value change
            document.getElementById("filter-field").addEventListener("change", updateFilter);
            document.getElementById("filter-value").addEventListener("keyup", updateFilter);

            //Clear filters on "Clear Filters" button click
            document.getElementById("filter-clear").addEventListener("click", function () {
              fieldEl.value = "";
              valueEl.value = "";

              table.clearFilter();
            });

            //Trigger setFilter function with correct parameters
            function updateFilter() {
              var filterVal = fieldEl.options[fieldEl.selectedIndex].value;
              var typeVal = "like";


              if (filterVal) {
                table.setFilter(filterVal, typeVal, valueEl.value);
              } 
            }

            table.on('rowClick', (e, id, data, row) => {
              $('#modal-default').modal('show');
              this.setCourse(
                id._row.data.id,
                id._row.data.title,
                id._row.data.code,
                id._row.data.course_description
              )
            })
          }, 200);
        })
        .catch(error => {
          console.error('Error fetching data:', error);
        });
    },
    methods: {
      formatReadableDate(dateString) {
        const date = new Date(dateString);
        const options = {
          year: 'numeric',
          month: 'long',
          day: 'numeric',
          hour: '2-digit',
          minute: '2-digit',
        };
        return date.toLocaleDateString('en-US', options);
      },
      resetState() {
        this.title = ''
        this.code = ''
        this.course_description = ''
      },
      setCourse(id, title, code, course_description) {
        this.id = id
        this.title = title
        this.code = code
        this.course_description = course_description
      },
      async updateCourse() {

        const tokenField = document.querySelector('input[name="csrfmiddlewaretoken"]');

        let csrfToken = tokenField.value;

        const response = await fetch(`/courses/update/${this.id}`, {
          method: 'POST',
          headers: {
            'Content-Type': 'Application/Json',
            'X-CSRFToken': csrfToken,
            'X-Requested-With': 'XMLHttpRequest'
          },
          body: JSON.stringify({
            title: this.title,
            code: this.code,
            course_description: this.course_description
          })
        });
        
        window.location.reload()
      }
    }
  })

  app.mount('#app'); 
</script>
{% endblock javascripts %}