api/urls.py
from django.urls import path

from . import views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
    openapi.Info(
        title="Allotr API",
        default_version="v1",
        description="A REST API for the Allotr Course Allocation system",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="ssali.jkigundu@student.utamu.ac.ug"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("allocations", views.AllocationListView.as_view(), name="allocation-list"),
    path("courses/", views.CourseListView.as_view(), name="course_api_list"),
    path("intakes/", views.IntakeListView.as_view(), name="intake_api_list"),
    path(
        "enrollments/", views.EnrollmentListView.as_view(), name="enrollment_api_list"
    ),
    path("programs/", views.ProgramListView.as_view(), name="program_api_list"),
    path(
        "program/<int:program_id>/",
        views.ProgramDetailView.as_view(),
        name="program_detail",
    ),
    path(
        "programs-in-department/department/<int:department_id>/",
        views.ProgramsInDepartmentView.as_view(),
        name="programs_in_department_api_list",
    ),
    path(
        "enrollment/<int:pk>/",
        views.EnrollmentDetailUpdateView.as_view(),
        name="enrollment_api_list",
    ),
    path(
        "programcourses/",
        views.ProgramCourseListView.as_view(),
        name="program_course_api_list",
    ),
    path(
        "courses-in-program/<int:program_id>/",
        views.CoursesInProgramListView.as_view(),
        name="courses_in_program",
    ),
    path(
        "list_allocations/",
        views.ListAllocationView.as_view(),
        name="list_allocations_matching",
    ),
    path("lecturers/", views.LecturerList.as_view(), name="lecturer_api_list"),
    path(
        "lecturers/<int:lecturer_id>/",
        views.LecturerDetailView.as_view(),
        name="lecturer_api_detail",
    ),
    path(
        "structures/<int:program_id>/",
        views.StructureView.as_view(),
        name="structure_view",
    ),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path("auth/", include("users.urls"), name="auth"),
    path("", include("home.urls"), name="home"),
    path("i18n/", include("django.conf.urls.i18n")),
    path("courses/", include("courses.urls")),
    path("programs/", include("programs.urls")),
    path("departments/", include("departments.urls")),
    path("schools/", include("schools.urls")),
    path("intakes/", include("intakes.urls")),
    path("enrollments/", include("enrollments.urls")),
    path("allocations/", include("allocations.urls")),
    path("lecturers/", include("lecturers.urls")),
    path("api/", include("api.urls")),
]

schools/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.SchoolListView.as_view(), name="school_list"),
    path("<int:pk>/", views.SchoolDetailView.as_view(), name="school_detail"),
    path("create/", views.create_school, name="create_school"),
    path("update/<int:school_id>/", views.updated_school, name="update_school"),
    path("delete/<int:school_id>/", views.delete_school, name="delete_school"),
]

schools/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=255, unique=True)
    code = models.CharField(max_length=5, unique=True)
    dean = models.CharField(max_length=250)
    contact_email = models.EmailField(max_length=80)
    details = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("school_detail", kwargs={"pk": self.pk})

schools/forms.py
from django import forms

from .models import School


class SchoolCreateForm(forms.ModelForm):
    class Meta:
        model = School
        fields = ["name", "code", "dean", "contact_email", "details"]
        widgets = {"details": forms.Textarea(attrs={"rows": 5})}

schools/views.py
import json
from typing import Any

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView

from .forms import SchoolCreateForm
from .models import School

# Create your views here.


class SchoolListView(LoginRequiredMixin, ListView):
    template_name = "schools/index.html"
    queryset = School.objects.all()
    context_object_name = "schools"

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)

        context["form"] = SchoolCreateForm()

        return context


class SchoolDetailView(LoginRequiredMixin, DetailView):
    template_name = "schools/details.html"
    context_object_name = "schools"
    queryset = School.objects.all()


@login_required
def create_school(request: HttpRequest):
    data = json.loads(request.body)

    new_school = School(**data)

    new_school.save()

    messages.success(request, "School created successfully")
    return JsonResponse({"message": "School created successfuly"})


@login_required
def updated_school(request: HttpRequest, school_id):
    data = json.loads(request.body)

    school = School.objects.filter(id=school_id).update(**data)

    messages.success(request, "School updated successfully")

    return JsonResponse({"message": f"School `{school}` updated successfully"})


@login_required
def delete_school(request: HttpRequest, school_id):
    school = get_object_or_404(School, id=school_id)

    school.delete()

    messages.success(request, "School updated successfully")

    return JsonResponse({"message": "School deleted"})

templates/schools/details.html
{% extends 'layouts/base.html' %}

{% block title %} Tables {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="container-fluid py-4">

        
      {% include "includes/footer.html" %}

    </div>
    
{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

templates/schools/index.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Schools {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="container-fluid py-4" id="app">

  <div class="row">
    <div class="col-12">
      <div class="card mb-4">
        <div class="card-header pb-0">
          <h6>Schools</h6>
        </div>
        <div class="card-header pb-0">
          <button type="button" class="btn btn-sm bg-gradient-dark" data-bs-toggle="modal"
            data-bs-target="#createSchoolModal">
            Add School
          </button>
        </div>
        <div class="card-body px-0 pt-0 pb-2">
          <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
              <thead>
                <tr>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">School Name</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Code</th>
                </tr>
              </thead>
              <tbody>

                {% for school in schools %}
                <tr>
                  <td>
                    <div class="d-flex px-2 py-1">
                      <div>
                        <img src="{% static 'assets/img/grad.png' %}" class="avatar avatar-sm me-3" alt="user1">
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="mb-0 text-sm"><a href="{% url 'school_detail' pk=school.id%}">{{ school.name }}</a>
                        </h6>
                        <p class="text-xs text-secondary mb-0">{{school.contact_email}}</p>
                      </div>
                    </div>
                  </td>
                  <td>
                    <p class="text-xs font-weight-bold mb-0">{{ school.code }}</p>
                  </td>
                  <td class="align-middle">
                    <button type="button" class="btn btn-sm bg-gradient-dark" data-bs-toggle="modal"
                      data-bs-target="#exampleModal"
                      @click="setSchoolData(`{{ school.id }}`, `{{ school.name }}`, `{{school.dean}}`, `{{school.contact_email}}`, `{{school.code}}`, `{{school.details}}`)">
                      <i class="fas fa-eye fa-xs"></i>
                    </button>
                  </td>
                </tr>
                {% endfor %}

              </tbody>
            </table>
            <div class="modal modal modal-lg fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
              aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Update School Details</h5>
                    <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <form id="update-form">
                      {% csrf_token %}


                      <div class="row">
                        <div id="div_id_name" class="col"> <label for="id_name" class=" requiredField">
                          Name<span class="asteriskField">*</span> </label>
                        <div>
                          <input type="text" name="name" maxlength="500" class="textinput form-control" required
                            id="id_name" :value=[[name]]>
                        </div>
                      </div>
                      <div id="div_id_code" class="col"> <label for="id_code" class=" requiredField">
                          Code<span class="asteriskField">*</span> </label>
                        <div>
                          <input type="text" name="code" maxlength="255" class="textinput form-control" required
                            id="id_code" :value=[[code]] @input="event => code = event.target.value">
                        </div>
                      </div>
                      </div>
                      <div id="div_id_dean" class="form-group"> <label for="id_dean" class=" requiredField">
                          Dean<span class="asteriskField">*</span> </label>
                        <div>
                          <input type="text" name="dean" maxlength="255" class="textinput form-control" required
                            id="id_dean" :value=[[dean]] @input="event => dean = event.target.value">
                        </div>
                      </div>
                      <div id="div_id_contact_email" class="form-group"> <label for="id_contact_email"
                          class=" requiredField">
                          Contact email<span class="asteriskField">*</span> </label>
                        <div>
                          <input type="email" name="contact_email" maxlength="80" class="emailinput form-control"
                            required id="id_contact_email" :value=[[contact_email]]>
                        </div>
                      </div>
                      <div id="div_id_details" class="form-group"> <label for="id_details" class=" requiredField">
                          Details<span class="asteriskField">*</span> </label>
                        <div>
                          <textarea name="details" cols="40" rows="5" class="textarea form-control" required
                            id="id_details">[[details]]</textarea>
                        </div>
                      </div>

                    </form>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-sm bg-gradient-secondary"
                      data-bs-dismiss="modal">Close</button>
                    <a href="#" class="btn bg-gradient-danger" data-bs-toggle="modal"
                      data-bs-target="#deleteModal">Delete School</a> <button type="button"
                      class="btn btn-sm bg-gradient-dark" @click="updateSchool()">Update</button>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal modal-lg fade" id="createSchoolModal" tabindex="-1" role="dialog"
              aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add School</h5>
                    <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <form action="" method="post" id="create-form">
                      {% csrf_token %}
                      <div class="row">
                        <div class="col">
                          {{form.name |as_crispy_field}}
                        </div>
                        <div class="col">
                          {{form.code |as_crispy_field}}
                        </div>
                      </div>
                      <div class="row">
                        <div class="col">
                          {{ form.dean|as_crispy_field }}
                        </div>
                        <div class="col">
                          {{ form.contact_email|as_crispy_field }}
                        </div>
                        <div class="form-group">
                          {{form.details|as_crispy_field}}
                        </div>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-link text-danger" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-sm bg-gradient-dark" @click="createSchool()">Save</button>
                      </div>
                    </form>
                  </div>

                </div>
              </div>
            </div>
            
            {% comment %}
              modal for deleting a school
            {% endcomment %}
              
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="modal-notification"
              aria-hidden="true">
              <div class="modal-dialog modal-danger modal-dialog-centered modal-" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h6 class="modal-title" id="modal-title-notification">Delete School</h6>
                    <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close"
                      @click="resetState()">
                      <span aria-hidden="true">×</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <div class="py-3 text-center">
                      <i class="ni ni-bell-55 ni-3x"></i>
                      <h4 class="text-gradient text-danger mt-4">Are you sure you want to delete this School?</h4>
                      <p>[[name]]</p>
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn bg-gradient-danger" @click="deleteSchool()">Ok, Delete</button>
                    <button type="button" class="btn bg-gradient-dark text-white ml-auto"
                      data-bs-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script>
  const app = Vue.createApp({
    mounted() {
      console.log(this.name)
      console.log(this.contact_email)
    },
    data() {
      return {
        count: 0,
        id: '',
        name: '',
        dean: '',
        code: '',
        contact_email: '',
        details: ''
      }
    },
    delimiters: ['[[', ']]'],
    methods: {
      setSchoolData(id, name, dean, email, code, details) {
        this.id = id
        this.name = name
        this.dean = dean
        this.contact_email = email
        this.code = code
        this.details = details


        console.log(id, name, dean)

      },

      async createSchool() {
        // create a new school
        const createForm = document.getElementById('create-form');

        const tokenField = document.querySelector('input[name="csrfmiddlewaretoken"]');

        let csrfToken = tokenField.value;

        const formData = new FormData(createForm);

        let name = formData.get('name')
        let code = formData.get('code')
        let dean = formData.get('dean')
        let contact_email = formData.get('contact_email')
        let details = formData.get('details')

        const response = await fetch('/schools/create/', {
          headers: {
            'Content-Type': 'Application/Json',
            'X-CSRFToken': csrfToken,
            'X-Requested-With': 'XMLHttpRequest'
          },
          method: "POST",
          body: JSON.stringify({ name, code, dean, contact_email, details })
        })

        console.log(await response.json())

        createForm.reset()

        window.location.reload()
      },
      async updateSchool() {
        const createForm = document.getElementById('update-form');

        const tokenField = document.querySelector('input[name="csrfmiddlewaretoken"]');

        let csrfToken = tokenField.value;

        const formData = new FormData(createForm);

        let name = formData.get('name')
        let code = formData.get('code')
        let dean = formData.get('dean')
        let contact_email = formData.get('contact_email')
        let details = formData.get('details')
        let id = this.id;

        const response = await fetch(`/schools/update/${id}/`, {
          headers: {
            'Content-Type': 'Application/Json',
            'X-CSRFToken': csrfToken,
            'X-Requested-With': 'XMLHttpRequest'
          },
          method: "POST",
          body: JSON.stringify({ name, code, dean, contact_email, details })
        })

        console.log(await response.json())

        createForm.reset()

        window.location.reload()
      },
      async deleteSchool(){
        const response = await fetch(`/schools/delete/${this.id}/`);

        const data = response.json();

        console.log(data)

        window.location.reload()
      } 
    }
  },





  ).mount('#app')


</script>

{% endblock javascripts %}